<?xml version="1.0"?>
<robot name="limo_xacro" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="limo_wheel" params="parent_prefix wheel_prefix reflect *joint_pose">
        <link name="${wheel_prefix}_wheel_link">
            <inertial>
                <origin xyz="0 0 0" />
                <mass value="0.5" />
                <inertia ixx="0.01055" ixy="0" ixz="0" iyy="0.00075" iyz="0" izz="0.01055" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find limo_description)/meshes/limo_wheel.dae" />
                </geometry>
            </visual>
            <collision>
              <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
              <geometry>
                  <cylinder length="${wheel_length}" radius="${wheel_radius}" />
              </geometry>
            </collision>


        </link>

        <joint name="${wheel_prefix}_wheel" type="continuous">
            <parent link="${parent_prefix}"/>
            <child link="${wheel_prefix}_wheel_link"/>
            <xacro:insert_block name="joint_pose"/>
            <axis xyz="0 ${reflect*1} 0"/>
        </joint>
    </xacro:macro>


    <xacro:macro name="limo_velodyne" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_base_link'>
            <inertial>
            <mass value="0.83"/>
            <origin xyz="0 0 0.03585"/>
            <inertia ixx="0.000908059425" ixy="0" ixz="0" iyy="0.000908059425" iyz="0" izz="0.0011049624"/>
            </inertial>
            <visual>
            <geometry>
                <mesh filename="package://velodyne_description/meshes/VLP16_base_1.dae"/>
            </geometry>
            </visual>
            <visual>
            <geometry>
                <mesh filename="package://velodyne_description/meshes/VLP16_base_2.dae"/>
            </geometry>
            </visual>
            <collision>
            <origin rpy="0 0 0" xyz="0 0 0.03585"/>
            <geometry>
                <cylinder length="0.0717" radius="0.0516"/>
            </geometry>
            </collision>
        </link>

        <link name="velodyne">
            <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
            </inertial>
            <visual>
            <origin xyz="0 0 -0.0377"/>
            <geometry>
                <mesh filename="package://velodyne_description/meshes/VLP16_scan.dae"/>
            </geometry>
            </visual>
        </link>


        <joint type="fixed" name="velodyne_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_base_link"/>
            <parent link="${parent_prefix}"/>
            <origin rpy="0 3.141592653589793 0" xyz="0 0 -0.4"/>
        </joint>
        <joint name="velodyne_base_scan_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0.0377"/>
            <parent link="${frame_prefix}_base_link"/>
            <child link="velodyne"/>
        </joint>
        <!-- <gazebo reference="${frame_prefix}_base_link">
            <material>Gazebo/Yellow</material>
        </gazebo> -->
    </xacro:macro>





    <xacro:macro name="limo_depth_camera" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"
                />
            </inertial>
            <visual name='depth_camera_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
                <material name='depth_camera_material'>
                    <ambient>0.1 0.1 0.1 1</ambient>
                    <diffuse>0.1 0.1 0.2 1</diffuse>
                    <specular>0 0 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
            <collision name='depth_camera_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
            </collision>

        </link>
    
        <joint type="fixed" name="depth_camera_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <link name="depth_link"></link>

        <joint name="${frame_prefix}_to_camera_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2} "/>
            <parent link="${frame_prefix}_link"/>
            <child link="depth_link"/>
          </joint>

        <gazebo reference="${frame_prefix}_link">
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="limo_imu" params="parent_prefix frame_prefix  *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.01"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-7" ixy="0" ixz="0"
                    iyy="1e-7" iyz="0"
                    izz="1e-7"
                />
            </inertial>
            <visual name='imu_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <!-- <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry> -->
                <material name='imu_material'>
                    <ambient>0.1 0.1 0.1 1</ambient>
                    <diffuse>0.1 0.1 0.2 1</diffuse>
                    <specular>0 0 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
            <collision name='imu_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>
        <joint type="fixed" name="imu_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <gazebo reference="${frame_prefix}_link">
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>
</robot>