map_server:
  ros__parameters:
    frame_id: map   
    topic_name: map
    use_sim_time: True
    yaml_filename: "/home/ubuntu/ros2_ws/src/turtlebot3/turtlebot3_navigation2/map/map.yaml"
  
map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False